// Tous les textes de l'interface, regroupés pour une future traduction.

export const T = {
  marque: "Rêverie",
  signature: "Le voyage qui vous ressemble",
  accueil: {
    titre: "Dites vos envies,",
    titreManuscrit: "on trouve l'endroit.",
    sousTitre:
      "Pas besoin de savoir où aller. Dites-nous ce que chacun aime — et ce qu'il n'aime pas — et Rêverie vous propose des voyages qui plaisent à tout le groupe.",
    bouton: "Commencer mon voyage",
  },
  parcours: {
    etapes: ["Le groupe", "Les envies", "Le cadre"],
    progression: (n: number, total: number, nom: string) => `Étape ${n} sur ${total} : ${nom}`,
    suivant: "Continuer",
    precedent: "Retour",
    chercher: "Trouver nos voyages",
    aCorriger: "Quelques points à corriger :",
    recherche: "On cherche les endroits qui vous ressemblent…",
    arreter: "Arrêter",
  },
  groupe: {
    titre: "Qui part en voyage ?",
    adultes: "Adultes",
    enfants: "Enfants",
    ageEnfant: (n: number) => `Âge de l'enfant ${n}`,
    ans: (n: number) => (n === 0 ? "moins d'1 an" : `${n} an${n > 1 ? "s" : ""}`),
    agesAide: "L'âge change les prix et les activités proposées.",
    profils: "Les profils d'envies",
    profilsAide: (max: number) =>
      `Chacun peut avoir ses propres envies (jusqu'à ${max} profils). Les autres voyageurs partagent les envies communes.`,
    prenom: "Prénom",
    avatar: "Avatar",
    avatarDe: (prenom: string, a: string) => `Avatar ${a} pour ${prenom}`,
    ajouterProfil: "Ajouter un profil",
    retirerProfil: (prenom: string) => `Retirer ${prenom}`,
    options: "Bon à savoir",
    animal: "Nous voyageons avec un animal",
    accessibilite: "Besoins d'accessibilité",
    regime: "Régime alimentaire",
    langues: "Langues parlées",
  },
  voyage: {
    titre: "Qu'avez-vous envie de vivre ?",
    voyageurs: "Profils d'envies",
    aideEnvies: "Touchez une fois pour « J'aime », deux fois pour « Je n'aime pas », trois fois pour revenir à neutre.",
    resumeEnvies: (aime: number, naime: number) =>
      `${aime} envie${aime > 1 ? "s" : ""} · ${naime} refus`,
    reve: "Mon rêve en quelques mots",
    reveExemple: "Nager avec des tortues, dormir dans une cabane perchée…",
    refus: "Ce que je ne veux surtout pas",
    refusExemple: "Pas de foule, pas plus de 5 h de trajet…",
    caracteresRestants: (n: number) => `${n} caractères restants`,
  },
  cadre: {
    titre: "Le cadre du voyage",
    type: "Type de voyage",
    depart: "Départ",
    lieu: "Ville ou adresse de départ",
    lieuExemple: "Lyon, Nantes, 12 rue des Lilas à Lille…",
    rayon: (km: number) => `Jusqu'à ${km} km pour rejoindre une gare ou un aéroport`,
    quand: "Quand ?",
    aller: "Date d'aller",
    retour: "Date de retour",
    flexibilite: "Les dates peuvent bouger de",
    quelsMois: "Quel(s) mois ?",
    auMieuxExplication:
      "Rêverie cherchera la meilleure période sur les 12 prochains mois : la météo que vous voulez, de bons prix et moins de monde.",
    duree: "Combien de nuits ?",
    dureeAide: "Mettez le même nombre deux fois pour une durée exacte.",
    auMoins: "Au moins",
    auPlus: "Au plus",
    nuitsCalculees: (n: number) => `${n} nuit${n > 1 ? "s" : ""} sur place`,
    choisissezDates: "Choisissez vos dates d'aller et de retour.",
    budget: "Budget",
    budgetPour: "Le montant est",
    parGroupe: "pour tout le groupe",
    parPersonne: "par personne",
    montant: "Montant",
    montantExact: "Montant exact en euros",
    soitParPersonne: (s: string) => `soit environ ${s} par personne`,
    soitPourGroupe: (s: string) => `soit environ ${s} pour le groupe`,
    depassement: "Dépassement accepté",
    strict: "Strict",
    inclut: "Le budget couvre",
    transports: "Transports acceptés",
    transportsAide: "Pour éviter l'avion, il suffit de le décocher.",
    preferencesTrajet: "Préférences de trajet",
    dureeMax: "Durée de trajet maximale",
    sansLimite: "Sans limite",
    heures: (n: number) => `${n} h`,
    correspondancesMax: "Correspondances au maximum",
    nuit: "Trajet de nuit accepté",
    basCarbone: "Le plus bas carbone possible",
    hebergements: "Hébergements acceptés",
    etoiles: "Étoiles de l'hôtel",
    etoilesMin: "Au moins",
    etoilesMax: "Au plus",
    equipements: "Équipements souhaités",
    rythme: "Rythme",
  },
  etat: { aime: "J'aime", naime_pas: "Je n'aime pas", neutre: "Neutre" },
  resultats: {
    titre: (n: number) => `${n} voyage${n > 1 ? "s" : ""} qui vous ressemble${n > 1 ? "nt" : ""}`,
    aucun: "Aucune destination ne respecte toutes vos contraintes. Essayez d'assouplir un refus, le budget ou la durée de trajet.",
    enCours: (n: number) => (n === 0 ? "Les premières propositions arrivent…" : `${n} proposition${n > 1 ? "s" : ""} déjà prête${n > 1 ? "s" : ""}, on continue…`),
    arretee: "Recherche arrêtée : voici ce qui était déjà prêt.",
    dansBudget: "Dans le budget",
    dansMarge: "Dans la marge acceptée",
    horsBudget: "Au-dessus du budget",
    sur100: (n: number) => `Score ${n} sur 100`,
    periode: "Quand partir",
    meteo: "Météo attendue",
    sourceMeteo: (source: "normales" | "previsions", simulee: boolean) =>
      `${source === "previsions" ? "Prévisions" : "Normales de saison"}${simulee ? " — données simulées" : ""}`,
    formules: "Les 4 formules",
    nomsFormules: { economique: "Économique", equilibree: "Équilibrée", confort: "Confort", insolite: "Insolite" },
    total: "Total",
    compteBudget: (n: string) => `dont ${n} comptés dans votre budget`,
    trajet: "Aller (le retour est symétrique)",
    portePorte: "Porte à porte",
    correspondances: (n: number) => (n === 0 ? "direct" : `${n} correspondance${n > 1 ? "s" : ""}`),
    co2: "CO₂ (aller-retour, groupe)",
    hebergement: "Où dormir",
    nuits: (n: number) => `${n} nuit${n > 1 ? "s" : ""}`,
    unites: (n: number, type: string) => (n > 1 ? ` · ${n} ${type === "personne" ? "places" : "chambres ou logements"}` : ""),
    note: (n: number) => `note ${n.toLocaleString("fr-FR")}/10`,
    manque: "Manque :",
    activites: "Au programme",
    gratuit: "Visite libre",
    pour: (qui: string[]) => (qui.length ? ` — pour ${qui.join(", ")}` : ""),
    detail: "Détail poste par poste",
    postes: { transport: "Transport", hebergement: "Hébergement", activites: "Activités", repas: "Repas sur place" },
    horsBudgetPoste: "hors budget",
    releve: (date: string, source: string) => `Relevé le ${date} · ${source}`,
    nature: { reel: "Prix relevé", simulation: "Prix simulé", estimation: "Estimation" },
    etapes: "Les étapes",
    reponses: "Pour chacun",
    refusEvites: "Ce que vous évitez",
    compromis: "Les compromis, honnêtement",
    pourquoi: "Pourquoi ce score ?",
    compris: "Ce que nous avons compris de vos textes",
    exclues: (n: number) => `${n} destination${n > 1 ? "s" : ""} écartée${n > 1 ? "s" : ""}, et pourquoi`,
    departInconnu: (lieu: string) => `Nous n'avons pas reconnu « ${lieu} » : les trajets sont calculés depuis le centre de la France.`,
    partiel: (noms: string) => `Résultat partiel : ${noms} n'ont pas répondu à temps. Les montants concernés sont estimés.`,
    simulation:
      "Démonstration : aucun partenaire n'est encore connecté. Les prix, horaires et disponibilités sont SIMULÉS pour tester l'application ; ce ne sont pas de vraies offres.",
    mention: (heure: string) =>
      `Rêverie compare et vous redirigera vers des sites partenaires pour réserver ; Rêverie ne vend pas de voyage. Prix indicatifs relevés le ${heure}, susceptibles d'évoluer.`,
    modifier: "Modifier ma recherche",
  },

  erreurs: {
    reseau: "Impossible de joindre le serveur. Vérifiez votre connexion et réessayez.",
  },
} as const;
