// Tous les textes de l'interface, regroupés pour une future traduction.

export const T = {
  marque: "Rêverie",
  signature: "Le voyage qui vous ressemble",
  accueil: {
    titre: "Dites vos envies,",
    titreManuscrit: "on trouve l'endroit.",
    sousTitre:
      "Pas besoin de savoir où aller. Dites-nous ce que chacun aime — et ce qu'il n'aime pas — et Rêverie vous propose des voyages qui plaisent à tout le groupe.",
    bouton: "Commencer mon voyage",
  },
  parcours: {
    etapes: ["Le groupe", "Les envies", "Le cadre"],
    progression: (n: number, total: number, nom: string) => `Étape ${n} sur ${total} : ${nom}`,
    suivant: "Continuer",
    precedent: "Retour",
    chercher: "Trouver nos voyages",
    aCorriger: "Quelques points à corriger :",
    recherche: "On cherche les endroits qui vous ressemblent…",
    arreter: "Arrêter",
  },
  groupe: {
    titre: "Qui part en voyage ?",
    adultes: "Adultes",
    enfants: "Enfants",
    ageEnfant: (n: number) => `Âge de l'enfant ${n}`,
    ans: (n: number) => (n === 0 ? "moins d'1 an" : `${n} an${n > 1 ? "s" : ""}`),
    agesAide: "L'âge change les prix et les activités proposées.",
    profils: "Les profils d'envies",
    profilsAide: (max: number) =>
      `Chacun peut avoir ses propres envies (jusqu'à ${max} profils). Les autres voyageurs partagent les envies communes.`,
    prenom: "Prénom",
    avatar: "Avatar",
    avatarDe: (prenom: string, a: string) => `Avatar ${a} pour ${prenom}`,
    ajouterProfil: "Ajouter un profil",
    retirerProfil: (prenom: string) => `Retirer ${prenom}`,
    options: "Bon à savoir",
    animal: "Nous voyageons avec un animal",
    accessibilite: "Besoins d'accessibilité",
    regime: "Régime alimentaire",
    langues: "Langues parlées",
  },
  voyage: {
    titre: "Qu'avez-vous envie de vivre ?",
    voyageurs: "Profils d'envies",
    aideEnvies: "Touchez une fois pour « J'aime », deux fois pour « Je n'aime pas », trois fois pour revenir à neutre.",
    resumeEnvies: (aime: number, naime: number) =>
      `${aime} envie${aime > 1 ? "s" : ""} · ${naime} refus`,
    reve: "Mon rêve en quelques mots",
    reveExemple: "Nager avec des tortues, dormir dans une cabane perchée…",
    refus: "Ce que je ne veux surtout pas",
    refusExemple: "Pas de foule, pas plus de 5 h de trajet…",
    caracteresRestants: (n: number) => `${n} caractères restants`,
  },
  cadre: {
    titre: "Le cadre du voyage",
    type: "Type de voyage",
    depart: "Départ",
    lieu: "Ville ou adresse de départ",
    lieuExemple: "Lyon, Nantes, 12 rue des Lilas à Lille…",
    rayon: (km: number) => `Jusqu'à ${km} km pour rejoindre une gare ou un aéroport`,
    quand: "Quand ?",
    aller: "Date d'aller",
    retour: "Date de retour",
    flexibilite: "Les dates peuvent bouger de",
    quelsMois: "Quel(s) mois ?",
    auMieuxExplication:
      "Rêverie cherchera la meilleure période sur les 12 prochains mois : la météo que vous voulez, de bons prix et moins de monde.",
    duree: "Combien de nuits ?",
    dureeAide: "Mettez le même nombre deux fois pour une durée exacte.",
    auMoins: "Au moins",
    auPlus: "Au plus",
    nuitsCalculees: (n: number) => `${n} nuit${n > 1 ? "s" : ""} sur place`,
    choisissezDates: "Choisissez vos dates d'aller et de retour.",
    budget: "Budget",
    budgetPour: "Le montant est",
    parGroupe: "pour tout le groupe",
    parPersonne: "par personne",
    montant: "Montant",
    montantExact: "Montant exact en euros",
    soitParPersonne: (s: string) => `soit environ ${s} par personne`,
    soitPourGroupe: (s: string) => `soit environ ${s} pour le groupe`,
    depassement: "Dépassement accepté",
    strict: "Strict",
    inclut: "Le budget couvre",
    transports: "Transports acceptés",
    transportsAide: "Pour éviter l'avion, il suffit de le décocher.",
    preferencesTrajet: "Préférences de trajet",
    dureeMax: "Durée de trajet maximale",
    sansLimite: "Sans limite",
    heures: (n: number) => `${n} h`,
    correspondancesMax: "Correspondances au maximum",
    nuit: "Trajet de nuit accepté",
    basCarbone: "Le plus bas carbone possible",
    hebergements: "Hébergements acceptés",
    etoiles: "Étoiles de l'hôtel",
    etoilesMin: "Au moins",
    etoilesMax: "Au plus",
    equipements: "Équipements souhaités",
    rythme: "Rythme",
  },
  etat: { aime: "J'aime", naime_pas: "Je n'aime pas", neutre: "Neutre" },
  resultats: {
    titre: (n: number) => `${n} voyages qui vous ressemblent`,
    aucun: "Aucune destination du catalogue ne respecte tous vos refus. Essayez d'en retirer un.",
    dansBudget: "Dans le budget",
    dansMarge: "Dans la marge acceptée",
    horsBudget: "Au-dessus du budget",
    estimation: (nuits: number) => `Estimation pour ${nuits} nuit${nuits > 1 ? "s" : ""}`,
    reponses: "Pour chacun",
    refusEvites: "Ce que vous évitez",
    compromis: "Les compromis, honnêtement",
    pourquoi: "Pourquoi ce score ?",
    mention: (heure: string) =>
      `Résultats issus de notre catalogue hors ligne, générés le ${heure}. Les montants sont des estimations indicatives, pas des prix relevés chez un partenaire. Aucune réservation n'est effectuée par Rêverie.`,
    modifier: "Modifier ma recherche",
  },
  erreurs: {
    reseau: "Impossible de joindre le serveur. Vérifiez votre connexion et réessayez.",
  },
} as const;
